### ISSUE TITLE
NOT URGENT Wondering if Debug should be affecting all players and not just named side in UCR_setup.sqf

### ISSUE THREAD

**Issue by Will-Nichols** [1ncontinentia/Incon-Undercover#32] opened 2018-12-11 18:54 UTC
I have debug turned on to check if it is working as it should. The scripts are working great BTW.

All players in my mission are showing the debug for the incognito debug actions? Anyway to only have Debug firing on just the INDFOR players in a mission or is it a global thing?

- Players who are in BLUFOR slots that they are showing debug hints and being allowed to check if their disguises are good via scroll wheel option. Not a problem but it does limit them on the messages they can get at bottom of screen.
- Checked my UCR_setup.sqf: only mention in player settings is `_undercoverUnitSide = independent;`
- Checked my Civilian Disguise Settings and only showing `_civFactions = ["CIV_F"];`
- Check my Enemy Disguise Settings and only showing `_incogFactions = ["O_CNAirborne","O_TAPOLICE"];`
- BLUFOR does not spawn with any gear mentioned in the UCR_setup.sqf for either OPFOR or INDFOR to use.

**Comment by 1ncontinentia** [comment] 2018-12-11 18:58
Is that with the edit I suggested in initPlayerLocal.sqf? If so, revert to the original one and make sure all undercover units have 

this setVariable [“isSneaky”,true,true]; 

In their init boxes. The edit I suggested makes all units undercover, so that would cause the behaviour you are seeing. 

Also Blufor and Ind are allied right? Three way wars don’t work..

**Comment by Will-Nichols** [comment] 2018-12-11 19:02
>           Is that with the edit I suggested in initPlayerLocal.sqf? If so, revert to the original one and make sure all undercover units have
>this setVariable [“isSneaky”,true,true];
> In their init boxes. The edit I suggested makes all units undercover, so that would cause the behaviour you are seeing.
> Also Blufor and Ind are allied right? Three way wars don’t work..

- Yes this is with that edit and all undercover units have that set in their init field in their init boxes
- Yes Blufor and Indfor are allied. I am not pushing a TvT setup with ALiVE...want to talk about a pain in the butt to manage...that is another story for another day.

**Comment by 1ncontinentia** [comment] 2018-12-11 19:08
Okay cool. In that case I’m gonna close this issue as the edit was a debugging measure meant to do exactly as you describe, which we don’t need now that we (hopefully) found the cause of your woes.. If you have any other issues or if the issue persists after you revert to the original initPlayerLocal.sqf from the most recent version (it almost certainly won’t) then feel free to open another issue.

**Closed as completed by 1ncontinentia** 2018-12-11 19:08 UTC
